apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/tk8s/kubernetes/media/jellyfin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
