apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: generic-device-plugin
  namespace: flux-system
spec:
  interval: 10m
  path: infrastructure/core/generic-device-plugin
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system