apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb-config
  interval: 10m
  path: infrastructure/core/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system