apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubernetes-reflector
  namespace: flux-system
spec:
  dependsOn:
    - name: snapshot-controller
  interval: 10m
  path: infrastructure/core/kubernetes-reflector
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system