apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-config
  namespace: flux-system
spec:
  dependsOn:
    - name: ingress-nginx
    - name: longhorn
  interval: 10m
  path: infrastructure/core/longhorn-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system