apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  dependsOn:
    - name: ingress-nginx
  interval: 10m
  path: infrastructure/core/longhorn
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system