apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-config
  namespace: flux-system
spec:
  interval: 10m
  path: infrastructure/core/media-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system