apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
  interval: 10m
  path: infrastructure/core/metallb-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system