apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-contoller
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
  interval: 10m
  path: infrastructure/core/snapshot-contoller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system