apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: volsync-config
  namespace: flux-system
spec:
  dependsOn:
    - name: volsync
  interval: 10m
  path: infrastructure/core/volsync-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system