apiVersion: networking.k8s.io/v1
kind: Ingress
spec:
  ingressClassName: internal
  rules:
  - host: podinfo.{DOMAIN_0}
    http:
      paths:
      - backend:
          service:
            name: podinfo
            port:
              number: 9898
        path: /
        pathType: Prefix
