apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
      interval: 5m
  releaseName: podinfo
  values:
    extraEnvs:
      - name: MULTIPLE_VALUES
        value: ${test}
    ingress:
      main:
        ingressClassName: internal
        hosts:
          - host: podinfo.${DOMAIN_0}
