apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
  namespace: flux-system
spec:
  suspend: false
  interval: 10m
  path: clusters/tk8s/kubernetes/general/immich/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
