apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: vaultwarden
    namespace: vaultwarden
spec:
    interval: 10m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: vaultwarden
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 10m
    install:
        createNamespace: true
        crds: CreateReplace
        timeout: 20m
        remediation:
            retries: 2
    upgrade:
        crds: CreateReplace
        timeout: 20m
        remediation:
            retries: 2
    values:
        global:
            stopAll: false
        credentials:
          backblaze:
            type: s3
            url: "${S3_URL}"
            bucket: "${S3_BUCKET}-vaultwarden"
            accessKey: "${S3_ACCESS_KEY}"
            secretKey: "${S3_SECRET_KEY}"
            encrKey: "${S3_ENCRYPTION_KEY}"
        ingress:
            main:
                enabled: true
                integrations:
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
                    certManager:
                        enabled: true
                        certificateIssuer: letsencrypt-domain-0
                hosts:
                    - host: vault.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
            admin:
                enabled: true
                primary: false
                targetSelector:
                    main: main
                integrations:
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
                        #              middlewares:[]
                        #              - name: vaultwarden
                        #                namespace: traefik
                        #              - name: auth
                        #                namespace: traefik
                        #              - name: real-ip
                        #                namespace: traefik
                        #              enableFixedMiddlewares: true
                        forceTLS: true
                        allowCors: false
                    certManager:
                        enabled: true
                        certificateIssuer: letsencrypt-domain-0
                hosts:
                    - host: vault.${DOMAIN_0}
                      paths:
                        - path: /admin
                          pathType: Prefix
            cloudflare:
                enabled: true
                ingressClassName: cloudflare-tunnel
                rules:
                    - http: null
                      paths:
                        - path: /
                          pathType: Prefix
                backend:
                    service:
                        name: vaultwarden
                        port:
                            number: 10102
                hosts:
                    - host: vault.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
        persistence:
            data:
              volsync:
              - name: data
                type: restic
                cleanupTempPVC: false
                cleanupCachePVC: false
                credentials: backblaze
                dest:
                  enabled: true
                src:
                  enabled: true
                  trigger:
                    schedule: 40 1 * * *
        cnpg:
            main:
              cluster:
                singleNode: true
              mode: recovery
              backups:
                enabled: true
                revision: "3"
                credentials: backblaze
                scheduledBackups:
                  - name: daily-backup
                    schedule: "0 5 0 * * *"
                    backupOwnerReference: self
                    immediate: true
                    suspend: false
              recovery:
                method: object_store
                credentials: backblaze
        vaultwarden:
            admin:
                enabled: true
                token: ${VW_ADMIN_TOKEN}
                #        allowSignups: false
                #        log:
                #          level: info
                #        push:
                #          enabled: true
                #          installationId: ${VAULTWARDEN_PUSH_ID}
                #          installationKey: ${VAULTWARDEN_PUSH_KEY}
                #        yubico:
                #          clientId: ${YUBICO_ID}
                #          enabled: true
                #          secretKey: ${YUBICO_SECRET}
                #          server: ''
            smtp:
                enabled: true
                host: ${SMTP_HOST}
                from: ${SMTP_FROM}
                port: ${SMTP_PORT}
                security: ${SMTP_SECURITY}
                user: ${SMTP_USER}
                password: ${SMTP_PASS}
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            advanced: false
                            env:
                                EXPERIMENTAL_CLIENT_FEATURE_FLAGS: autofill-overlay,autofill-v2
