apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: vaultwarden
    namespace: vaultwarden
spec:
    interval: 10m
    chart:
        spec:
            chart: vaultwarden
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 10m
    install:
        createNamespace: true
        crds: CreateReplace
        timeout: 20m
        remediation:
            retries: 2
    upgrade:
        crds: CreateReplace
        timeout: 20m
        remediation:
            retries: 2
    values:
        global:
            stopAll: false
        credentials:
          backblaze:
            type: s3
            url: "${S3_URL}"
            bucket: "${S3_BUCKET}-vaultwarden"
            accessKey: "${S3_ACCESS_KEY}"
            secretKey: "${S3_SECRET_KEY}"
            encrKey: "${S3_ENCRYPTION_KEY}"
        ingress:
          main:
            enabled: true
            ingressClassName: internal
            integrations:
              traefik:
                enabled: false
              certManager:
                enabled: true
                certificateIssuer: letsencrypt-domain-0
            hosts:
              - host: vault.${DOMAIN_0}
                paths:
                  - path: /
                    pathType: Prefix 
          cloudflare:
            enabled: true
            ingressClassName: cloudflare
            integrations:
              traefik:
                enabled: false
            hosts:
            - host: vault.${DOMAIN_0}
              paths:
              - path: /
                pathType: Prefix
        persistence:
            data:
              volsync:
              - name: data
                type: restic
                cleanupTempPVC: false
                cleanupCachePVC: false
                credentials: backblaze
                dest:
                  enabled: true
                src:
                  enabled: true
                  trigger:
                    schedule: 40 1 * * *
        cnpg:
            main:
              cluster:
                singleNode: true
              mode: recovery
              backups:
                enabled: true
                revision: "9"
                credentials: backblaze
                scheduledBackups:
                  - name: daily-backup
                    schedule: "0 5 0 * * *"
                    backupOwnerReference: self
                    immediate: true
                    suspend: false
              recovery:
                method: object_store
                revision: "6"
                credentials: backblaze
        vaultwarden:
            admin:
                enabled: true
                token: ${VW_ADMIN_TOKEN}
            smtp:
                enabled: true
                host: ${SMTP_HOST}
                from: ${SMTP_FROM}
                port: ${SMTP_PORT}
                security: ${SMTP_SECURITY}
                user: ${SMTP_USER}
                password: ${SMTP_PASS}
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            advanced: false
                            env:
                                EXPERIMENTAL_CLIENT_FEATURE_FLAGS: autofill-overlay,autofill-v2
