apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: renovate
    namespace: flux-system
spec:
    type: oci
    interval: 2h
    url: https://mend.github.io/renovate-ce-ee