apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    test: ENC[AES256_GCM,data:wgJB+0o=,iv:BQ8qKyhuIff5kkfZfrLqR3PUY4C2rsjYJsOqT1X1mOo=,tag:dgO++K3UuaWuVMcM1h4T+g==,type:str]
    METALLB_RANGE: ENC[AES256_GCM,data:GN9JDxlVESCcbGs27DqKJQTnfc92BPdNV1vL126xRg==,iv:tVKPBRltDmchp0GVatAuDj0Kh3f5nUPii6VcXmZpjaA=,tag:LNgjt+AzB0eE5eTRqTVW4w==,type:str]
    NGINX_IP: ENC[AES256_GCM,data:0qVM/Gh0gIDt7NsbKLVw,iv:QD3D0obw33ihHay2huJ5keYlR4+WPW+VhXhkse9Us2g=,tag:FiYCLoHggNsbwy6HjVRPdA==,type:str]
    DOMAIN_0: ENC[AES256_GCM,data:QlSsVEDvbg==,iv:Y3wq54Im29nBBau0SfBDLwW1pj0sAJEOkPHHFRrMc6o=,tag:GWbGIr05ClpNLmsSJ3w40A==,type:str]
    DOMAIN_1: ENC[AES256_GCM,data:MYXfq6Sai1Nfx/N8pQ9P,iv:EbAajNX8lB8jF8hnPk5pBSIVVMDvlmgp1ShqTOk4Onk=,tag:QXiPs5rtUawVb5uW6mAtYw==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:DD5LeWyBwAyhPUAXZ0Ub6xEIOOM6KO1tOAMWEs7vJKe8CPIml1EJdg==,iv:Ox1pqKujlF1QaBI0Y3J9I/8HnXDGGqYiNDH6pSV+uzc=,tag:jjmu0sd8pQfrWzErmclFhw==,type:str]
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ENSayhZS8oqe8u/BYBa3CwNiXg==,iv:eU1kVm8db3Ph1XA+W4ntwrHQUUvOLBgtkaDwXaYp+bA=,tag:YgBXvPfLrvIYC0T5NbfAzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uprm5p9crdz7xn3ra9kfwv2axyg6re0jgn6tknf9tmsrn7dm2u3qktlpgx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRy95SDRXc1liV0w2bXMz
            d3hNN0txcG5oYnBOOVF2Uk0xL3haZTc2ZXhFCmY5aC9ScGhnQUlZa1hJRG1QejFo
            OFFod2Q4WUJvSVc1ekJTNjBYVFpxYTQKLS0tIEtQNW5jK1VKeUhUcWxPUGw4MlFv
            Qk0yWDBYNGNwK1pmUURHZElmVWkxRjQKC/yhW8G+5Ex82wEPhsCnlsp6wchTtyrx
            zZq4djD7+JuZ0MinKjvWv69qML/FWCg7h67YwuWzqY54TxM0GSbbNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-15T02:14:48Z"
    mac: ENC[AES256_GCM,data:aapdOW4zthbdZfR39/V7HHKtbatac4bm/r4JqusjWtUKzvQJMXSKTw+ZiA6NhZ24+oJHze37lQZkxsH5FCZuRQwHxGnublYXAAv2esWApHO6hEYTS5UeLVGGYmov13mUCY9qTfWpf4WTriLguZmimkr3CbrnIxf8oqBxgye07DM=,iv:bW3/rtpWYlv+MHV0f9lSZYWpUDTKF6j2cTYDQLBlTrY=,tag:LcdHflvGx93RilXsAGflpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
