apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: chromium
  namespace: flux-system
spec:
  suspend: true
  interval: 10m
  path: apps/general/chromium
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
