apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 10m
  path: apps/general/immich
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
