apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  dependsOn:
    - name: ingress-nginx
  interval: 10m
  path: apps/general/podinfo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system