apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qbittorrent
  namespace: flux-system
spec:
  dependsOn:
  - name: generic-device-plugin
  interval: 10m
  path: apps/media/qbittorrent
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system