apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sonarr
  namespace: flux-system
spec:
  interval: 10m
  path: apps/media/sonarr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system