apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 10m
  path: truek8s/apps/auth/authentik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
