apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: sonarr
    namespace: media
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: sonarr
#            version: 23.3.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      portal:
        open:
          enabled: false
      global:
        stopAll: false
      credentials:
        backblaze:
          type: s3
          url: "${S3_URL}"
          bucket: "${S3_BUCKET}-sonarr"
          accessKey: "${S3_ACCESS_KEY}"
          secretKey: "${S3_SECRET_KEY}"
          encrKey: "${S3_ENCRYPTION_KEY}"
      ingress:
        main:
          enabled: true
          integrations:
            traefik:
              enabled: true
              entrypoints:
              - websecure
              middlewares:
              - name: auth
                namespace: traefik
            certManager:
              enabled: true
              certificateIssuer: letsencrypt
          hosts:
            - host: sonarr.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
        cloudflare:
          enabled: true
          ingressClassName: cloudflare-tunnel
          rules:
            - http:
              paths:
              - path: /
                pathType: Prefix
          backend:
            service:
              name: sonarr
              port:
                number: 10102
          hosts:
            - host: sonarr.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
      persistence:
        config:
          volsync:
          - name: config
            type: restic
            cleanupTempPVC: true
            cleanupCachePVC: true
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 50 0 * * *
        media:
          enabled: true
          existingClaim: media-nfs-pvc
          mountPath: /Media
      metrics:
        main:
          enabled: false