apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: it-tools
    namespace: it-tools
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: it-tools
            version: 7.4.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      ingress:
        main:
          enabled: true
          integrations:
            traefik:
              enabled: true
              entrypoints:
              - websecure
            certManager:
              enabled: true
              certificateIssuer: letsencrypt
          hosts:
            - host: tools.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
        cloudflare:
          enabled: true
          ingressClassName: cloudflare-tunnel
          rules:
            - http:
              paths:
              - path: /
                pathType: Prefix
          backend:
            service:
              name: it-tools
              port:
                number: 18082
          hosts:
            - host: tools.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
