apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: chromium
    namespace: chromium
spec:
    interval: 5m
    chart:
        spec:
            chart: chromium
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      podOptions:
        hostUsers: true
      global:
        stopAll: false
      credentials:
        backblaze:
          type: s3
          url: "${S3_URL}"
          bucket: "${S3_BUCKET}-chromium"
          accessKey: "${S3_ACCESS_KEY}"
          secretKey: "${S3_SECRET_KEY}"
          encrKey: "${S3_ENCRYPTION_KEY}"
      ingress:
        main:
          enabled: true
          ingressClassName: internal
          integrations:
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: letsencrypt-domain-0
          hosts:
            - host: chrome.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
      workload:
        main:
          podSpec:
            containers:
              main:
                env:
                  CUSTOM_RES_H: "900"
                  CUSTOM_RES_W: "1920"
      persistence:
        datadir:
          volsync:
          - name: datadir
            type: restic
            cleanupTempPVC: false
            cleanupCachePVC: false
            credentials: backblaze
            dest:
              enabled: false
            src:
              enabled: false
              trigger:
                schedule: 10 0 * * *
