apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: chromium
    namespace: chromium
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: chromium
            version: 7.4.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      global:
        stopAll: false
      credentials:
        backblaze:
          type: s3
          url: "${S3_URL}"
          bucket: "${S3_BUCKET}-chromium"
          accessKey: "${S3_ACCESS_KEY}"
          secretKey: "${S3_SECRET_KEY}"
          encrKey: "${S3_ENCRYPTION_KEY}"
      ingress:
        main:
          enabled: true
          integrations:
            traefik:
              enabled: true
              entrypoints:
              - websecure
#              middlewares:
#              - name: auth
#                namespace: traefik
            certManager:
              enabled: true
              certificateIssuer: letsencrypt
          hosts:
            - host: chrome.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
        cloudflare:
          enabled: true
          ingressClassName: cloudflare-tunnel
          rules:
            - http:
              paths:
              - path: /
                pathType: Prefix
          backend:
            service:
              name: chromium
              port:
                number: 8080
          hosts:
            - host: chrome.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
      workload:
        main:
          podSpec:
            containers:
              main:
                env:
                  CUSTOM_RES_H: "900"
                  CUSTOM_RES_W: "1920"
      persistence:
        datadir:
          volsync:
          - name: datadir
            type: restic
            cleanupTempPVC: false
            cleanupCachePVC: false
            credentials: backblaze
            dest:
              enabled: false
            src:
              enabled: false
              trigger:
                schedule: 10 0 * * *
