apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: homepage
    namespace: homepage
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: homepage
            version: 10.1.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      workload:
        main:
          podSpec:
            containers:
              main:
                env:
                  # Set this to your host (example: home.mydomain.com)
                  HOMEPAGE_ALLOWED_HOSTS: home.${DOMAIN_0}
      global:
        stopAll: false
      credentials:
        backblaze:
          type: s3
          url: "${S3_URL}"
          bucket: "${S3_BUCKET}-homepage"
          accessKey: "${S3_ACCESS_KEY}"
          secretKey: "${S3_SECRET_KEY}"
          encrKey: "${S3_ENCRYPTION_KEY}"
      ingress:
        main:
          enabled: true
          integrations:
            traefik:
              enabled: true
              entrypoints:
              - websecure
#              middlewares:
#              - name: auth
#                namespace: traefik
            certManager:
              enabled: true
              certificateIssuer: letsencrypt-domain-0
          hosts:
            - host: home.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
      addons:
        codeserver:
          enabled: true
          ingress:
            enabled: true
            hosts:
            - host: homepage.code.${DOMAIN_0}
              paths:
              - path: /
                pathType: Prefix
            integrations:
              certManager:
                certificateIssuer: letsencrypt-domain-0
                enabled: true
              traefik:
                enabled: true
                entrypoints:
                - websecure
#                middlewares:
#                - name: auth
#                  namespace: 'traefik'
      persistence:
        config:
          volsync:
          - name: config
            type: restic
            cleanupTempPVC: false
            cleanupCachePVC: false
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 10 0 * * *
